### ISSUE TITLE
Unclear how to claim as a keybase user

### ISSUE THREAD

**Issue by troq** [handshake-org/hs-airdrop#12]
How does claiming work as a keybase user? From what I can tell, you added the public pgp keys for keybase users who have verified their Hackernews accounts, but it's unclear how to actually claim and on what device.

**Comment by dos1** [comment]
As far as I understand it, you should claim it using your PGP private key.

**Comment by troq** [comment]
Right, but according to the [testnet 4 update](https://github.com/handshake-org/hsd/issues/126), the keys for Keybase users who have connected their Hackernews accounts over 1.5 years old were added to the airdrop, but it's unclear which keys were used. If it's PGP keys, not every Keybase user will have that as Keybase [changed their key model in 2015](https://keybase.io/blog/keybase-new-key-model). Looking at the [source code](https://github.com/handshake-org/hs-airdrop/blob/master/bin/hs-airdrop#L371) @chjj wrote, it doesn't look like support for NaCl keys was added even though that's what most users will have.

**Comment by tynes** [comment]
Taking a look at the Keybase API docs, I found something interesting:

```
Keybase's interface currently supports one key per user.
Uploading a new key requires revoking/replacing an old one.
However, the public_keys object is designed to support
multiple in the future.
```

https://keybase.io/docs/api/1.0/user_objects

This seems like its outdated because there is an endpoint for adding a key.
https://keybase.io/docs/api/1.0/call/key/add

Digging in some more, NaCl uses Ed25519, which is supported.
https://github.com/handshake-org/hs-airdrop/blob/00f09bc8392bd6ba8dfafc5e2d26c2477418f89c/lib/key.js#L13

https://en.wikipedia.org/wiki/NaCl_(software)

If I understand the codepath correctly, keys that have supported algorithms
https://github.com/handshake-org/hs-airdrop/blob/e76ec6b1b8919e7af7fe7de21a6f692908d731a9/scripts/merkelize-airdrop#L482
and are valid
https://github.com/handshake-org/hs-airdrop/blob/e76ec6b1b8919e7af7fe7de21a6f692908d731a9/scripts/merkelize-airdrop#L489
will end up in the tree. What is unclear to me is if each user will only have 1 key or all of their keys included from Keybase.

I'm sure that people would like to test out claiming from their Keybase keys, do you mind commenting on this @chjj?

**Comment by NieDzejkob** [comment]
Any news on this issue?

**Comment by jonnydubowsky** [comment]
I too would love insight into how to claim as Keybase user w/ social proof from Hacker News?

**Comment by pinheadmz** [comment]
The process is the same as for GitHub users: run the script with your PGP key.
