### ISSUE TITLE
Validate correct claim

### ISSUE THREAD

**Issue by onurakpolat** [handshake-org/hs-airdrop#26]
Friends,

I was wondering if there is a way to verify that a claim has been made correctly, and if thats even possible with the two-weeks tx ban on mainnet. I've used my faucet address back then. I basically:

* created the base64 string with `hs-airdrop`

```
  ],
  "subindex": 0,
  "subproof": [],
  "key": {
    "type": "ADDRESS",
    "version": 0,
    "address": ...
....
```
* started a `hsd` full node 
* used `hs-client` to pass the prev. generated base64 key via hsd-rpc sendrawairdrop.

it returned a 64-character alphanumeric string. When I query my address on HNScan the balance is 0.

**Comment by pinheadmz** [comment]
Sounds like your test was actually successful, although if you check your full node logs you might see that the airdorp proof was rejected by the network because of the 2-week hold on transactions.

You can launch a local regtest chain (which has no txStart limit) and submit your proof to the regtest chain. Generate a block and then check your wallet balance!

The 64-character string you saw is a hash of the proof, and is used like a transaction hash to identify it.

**Comment by pinheadmz** [comment]
In fact on my own full node I grepped for such messages and found about a dozen airdrop proofs being rejected for this reason:

```
(peer) Rejecting AIRDROP 72891b81787be40d14c089057d423d722cf7dd94199d6e1d6127c74fe56c1618 (90.187.127.217:36846): code=invalid reason=no-tx-allowed-yet.
(net) Error: Verification failure: no-tx-allowed-yet (code=invalid score=0 hash=72891b81787be40d14c089057d423d722cf7dd94199d6e1d6127c74fe56c1618)
```

**Comment by onurakpolat** [comment]
Found it too, amazing thanks!
