### ISSUE TITLE
What value should I enter to claim my entire airdrop?

### ISSUE THREAD

**Issue by gg2001** [handshake-org/hs-airdrop#29]
I would like to claim all of the HNS airdropped to me, but I don't know how much I have received. What value should I pass to the hs-airdrop tool? The documentation is very unclear and makes no sense.

So should I just pass the value 4246.994314 to claim the whole airdrop? How are the transaction fees paid then? Please fix the README, even as a developer in the crypto space it makes zero sense.

**Comment by pinheadmz** [comment]
There are two kinds of airdrops.

If you registered at handshake.org you have a faucet address and backup seed. No action is needed on your part at all. The miners will include all the faucet airdrop outputs once transactions are enabled at block 2016. They are incentivized to do so with hard-coded fee amounts.

If you are NOT in the faucet tree, you need to use this tool to generate a proof with your GitHub key, and submit the proof to the network. All you need to pass it is your key file and a Handshake address:

`$ hs-airdrop [key-file] [addr]`

The fee is optional, a default fee is already set.

On behalf of the community, I apologize for the unclear documentation. As a developer in the crypto space you must know how hard it is to keep everything updated, especially a massive project like Handshake. We are working very hard to ensure everyone who qualifies gets their free tokens because we want everyone in the larger FOSS community to use Handshake.

Thank you for being a part of the project! If you are able to contribute a PR to the README in this repo, that would be a big help!

**Comment by gg2001** [comment]
Thanks for the quick reply, I wasn't in the faucet tree so this makes more sense now.

**Comment by josescasanova** [comment]
hey @pinheadmz, 

Regarding `The miners will include all the faucet airdrop outputs once transactions are enabled at block 2016` does your HNS address being included here https://github.com/handshake-org/hs-tree-data/blob/master/proof.json mean you are part of the faucet tree?
